[font]
size = 12.0

[font.bold]
family = "VictorMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "VictorMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "VictorMono Nerd Font"
style = "Italic"

[font.normal]
family = "VictorMono Nerd Font"
style = "Regular"

[mouse]
hide_when_typing= true

[window]
# title = "${pwd}"
dynamic_title = true
# decorations="none"
